apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-deployment
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: api-deployment
  targetCPUUtilizationPercentage: 80
