apiVersion: v1
kind: Service
metadata:
  name: web-service
  annotations:
      services.beta.kubernetes.io/aws-loadbalancer-type: nlb
      services.beta.kubernetes.io/aws-loadbalancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    name: web
  type: loadbalancer
  ports:
    - protocol: TCP
      port: 3000

